### ISSUE TITLE
Update xkbcommon

### ISSUE THREAD

**Issue by aleixpol** [flatpak/freedesktop-sdk-images#10]
Current version is 0.7, this is still offering 0.5.

**Comment by alexlarsson** [comment]
Hmm, it adds new API. I dunno. At some point we need to do a major version bump and update a lot of dependencies instead.

**Comment by aleixpol** [comment]
I guess it's more of a policy matter then.

From my point of view it should be fine to drag new dependencies as long as they don't break compatibility backwards (i.e. source or maybe abi).

I ran into the issue in a rather corner case, so feel free to close the issue.

**Comment by alexlarsson** [comment]
Well, the policy in general foruntimes is to be quite strict about updates, because the whole idea is to give some kind of guarantee that old built applications keep running (and for the sdk, old source versions keeps building). 

This is different from a distribution, because a distribution typically also control all users of the library, so if an updated library broke an app they'd get reports and can fix the app. However, for a runtime the users are not in our control, so we can't fix them, thus we need to be more strict about this.
